language: node_js
node_js:
  - 12.16.2
cache: npm

script: 
  - echo "skipping tests"

deploy:
  - provider: heroku
    skip_cleanup: true
    api_key:
      secure: 98a41c94-08b6-452e-9d0f-ad6297b78ef8
    app: react-editor-app